### ISSUE TITLE
Document using Extract and GitHub Actions 

### ISSUE THREAD

**Issue by anganti** [microsoft/vscode-apimanagement#64]
Document using Extract and GitHub Actions

**Comment by anganti** [comment]
Post running extract which should produce the arm templates could use az cli github action
https://github.com/marketplace/actions/azure-cli-action

```
# File: .github/workflows/workflow.yml

on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az group deployment create --resource-group apim-rg --template-file apim-myinstance-master.template.json --parameters ./apim-myinstace-parameters.json

```
